/**
 * Project Model
 * Represents a student project within a course.
 * Projects are either pitched by students (pending approval)
 * or assigned directly by an instructor.
 * All projects must belong to a course — no personal projects.
 * Related to: User (userId), Course (courseId),
 * CourseMaterial (via recommendations)
 */
const mongoose = require('mongoose')

const projectSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  courseId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Course',
    required: true
  },
  title: {
    type: String,
    required: [true, 'Project title is required'],
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  domain: {
    type: String,
    enum: ['web', 'mobile', 'ml', 'data', 'security',
      'systems', 'devops', 'general'],
    default: 'general'
  },
  language: {
    type: String,
    default: 'any'
  },
  skillLevel: {
    type: String,
    enum: ['beginner', 'intermediate', 'advanced'],
    default: 'beginner'
  },
  projectType: {
    type: String,
    enum: ['pitched', 'assigned'],
    required: true
    // pitched: student created and submitted for approval
    // assigned: instructor created and assigned to student
  },
  status: {
    type: String,
    enum: [
      'pitch_pending',
      // Student pitched idea, waiting for instructor approval
      'active',
      // Approved or directly assigned, work in progress
      'rejected',
      // Pitch was rejected by instructor
      'completed',
      // Student marked as done
      'paused'
      // On hold
    ],
    default: 'pitch_pending'
  },
  // Proposal document uploaded by student (optional)
  proposalDocId: {
    type: mongoose.Schema.Types.ObjectId
    // GridFS ID of uploaded proposal document
  },
  proposalFileName: {
    type: String
  },
  // Instructor feedback when rejecting a pitch
  instructorFeedback: {
    type: String,
    trim: true
  },
  // AI analysis of the proposal (generated by Gemini)
  aiAnalysis: {
    type: String
  },
  // Who approved or assigned this project
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  approvedAt: {
    type: Date
  },
  // If instructor assigned: who created and assigned it
  assignedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  // Cached recommendation IDs for this project
  recommendations: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CourseMaterial'
  }],
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
})

// Indexes for fast queries by user and by course
projectSchema.index({ userId: 1, status: 1 })
projectSchema.index({ courseId: 1, status: 1 })

// Auto-update updatedAt whenever the document is saved
projectSchema.pre('save', function (next) {
  this.updatedAt = new Date()
  next()
})

module.exports = mongoose.model('Project', projectSchema)
